# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ca7b322267b511f3fd0885878c8af243fdc799978ea9e4a02081a770bb5ef0a174130bdd86748595d5197594cfe4f748cdb167389c61d542bbc2362a5a38854

test:
  secret_key_base: d9953e3d6d726232531a3eeb2b9ba91147b9b17435f61c2fbdd076433fab55eb6838548ccc903690343d8f748d1fd10100beb0c4cf47a7061fdf037b4a28f827

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
